// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPUw9rYDQuW7wRNylVGBVrttJGrqTnTA',
    appId: '1:422474369537:android:e8cb6e0fdda830c802ce00',
    messagingSenderId: '422474369537',
    projectId: 'wanderly-app',
    storageBucket: 'wanderly-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu-5laCYsRlv5biOz8ANSdrDuzfkZHd5w',
    appId: '1:422474369537:ios:607961831d444fd802ce00',
    messagingSenderId: '422474369537',
    projectId: 'wanderly-app',
    storageBucket: 'wanderly-app.appspot.com',
    androidClientId: '422474369537-mgsr591m7eh4opeiqsg5mqs1tl65ngq0.apps.googleusercontent.com',
    iosClientId: '422474369537-a5qtdeealjupbbe4p1evviptpk2aifav.apps.googleusercontent.com',
    iosBundleId: 'com.nonic.wanderly',
  );

}